### ISSUE TITLE
Product Vision & Strategy

### ISSUE THREAD

**Issue by baguspr** [baguspr/DECO3500#16]

**Comment by gibrann24** [comment]
https://uservoice.com/blog/product-roadmap-strategy-vision

Product Vision (Max out at one to two sentences)
Product vision example:
- Linkedin: “To connect the world’s professionals to make them more productive and successful.”
- Amazon: ”Our vision is to be earth’s most customer centric company; to build a place where people can come to find and discover anything they might want to buy online.”

“Offer semi anonymous long-term dating-app which emphasise people’s compatibility instead of physical appearance”


Product Strategy
-> Product strategies is more specific than the product vision, but not to specific. 
-> Should cover the fundamentals:
	- Who are we trying to serve?
		**People who are looking for a long-term relationships and prefer compatibility instead of physical appearance as the main aspect to establish a connections.** 

	- What problems are we trying to address?
		**Some people does not like how the current dating-app works because its too physical appearance oriented.**

	- How are we planning to address the problems?
		**Establish a dating-app that emphasise on people’s compatibility by highlighting the prompts and personal details.**
