### ISSUE TITLE
Academic & Published Documents Research

### ISSUE THREAD

**Issue by baguspr** [baguspr/DECO3500#9]

**Comment by s2004146s** [comment]
[The important of look.pdf](https://github.com/baguspr/DECO3500/files/9694561/The.important.of.look.pdf)

This paper suggested that visual cues are important when first initiating a relationship and can impact their willingness to further develop the relationship.

The matching hypothesis claims that people with similar level of physical attractiveness are more likely to form a relationship. However, in the context of online dating applications, the initiator tends to send request to people with higher level of physical attractiveness than them. They are less restrained when online dating, to maximise the opportunity to seek more attractive individuals as much as possible.

In contrast, for the responders, they tend to respond to responders with similar physical attractiveness than them.

Research indicates that people with similar matched physical attractiveness are more likely to form a long-standing relationship

**Comment by s2004146s** [comment]
[Facial Appearance when Judging Sociability.pdf](https://github.com/baguspr/DECO3500/files/9694687/Facial.Appearance.when.Judging.Sociability.pdf)

People spontaneously infer personality traits from facial appearance even though these inferences are often inaccurate.

Studies showed that people believe that personality traits are reflected in facial cues.

For example, a smiling person does not only be seen as happy, but also as warm and trustworthy.

A slightly upturned corners of the mouth occur due to natural variation in facial appearance is also being treated as warm and trustworthy.

From research conducted in this paper, sociability (warmth, friendliness, likeability) was believed to be more reflected in facial appearance than morality (trustworthiness, honesty, sincerity) or competency (competence, intelligence, skillfulness). Participants were also more confident when judging sociability, as well as the accuracy of their judgements.

In the hiring context, photographs were valued more when employers are looking for a sociable employee.

In the online dating context, if people are seeking people that are sociable (warmth, friendliness, likeability), visual appearances play an important role

**Comment by s2004146s** [comment]
[Gay & Lesbian.pdf](https://github.com/baguspr/DECO3500/files/9694815/Gay.Lesbian.pdf)

The ideal male bodies are muscular and lean. 

There are significant levels of body dissatisfaction among gay and bisexual men. Gay men experience more dissatisfaction with specific body parts, like waist and arm size.

Online dating apps became potential sources of body shaming, racism, and colorism.

Gay and bisexual men have significantly higher prevalence eating disorders than heterosexual men as they strive to have the ideal men body.

Minority Stress Model suggests that gay and bisexual men exposed to stressers (minority stressors of internalized
homophobia, stigma, and experiences of discrimination) report higher body dissatisfaction.

Objectification Theory suggests that they become preoccupied with how their bodies look as opposed to how they function, promoting body shame and disorder eating behaviours.

Mobile dating apps rely heavily on picture-sharing may result in body dissatisfaction via Objectification.

From research results, nearly all then men desire to change their body weight and shape. Over half of the men in the participants, experienced at least one experience of racial/ethnic discrimination or body weight and shape discrimination on mobile dating apps.
